function save_all_images_in_one_tex_file(tex_name, number_of_images)
% char(10) is a line break
    export = {'%!TEX TS-program = lualatex';                                 ...
                ['%!TeX encoding = utf8' char(10)];                          ...
                '\RequirePackage{luatex85}';                                 ...
                '\documentclass{article}';                                   ...
                '\usepackage{float}';                                        ...
                '\usepackage{lipsum}';                                       ...
                '\usepackage{pgfplots}';                                     ...
                '\pgfplotsset{compat=newest}';                               ...
                '\usepackage{siunitx}';                                      ...
                '\usetikzlibrary{plotmarks}';                                ...
                '\usetikzlibrary{arrows.meta}';                              ...
                '\usepgfplotslibrary{patchplots}';                           ...
                '\usepackage{grffile}';                                      ...
                ['\usepackage{amsmath}' char(10)];                           ...              
                ['\begin{document}' char(10)];
               };

    for idx = 1:number_of_images
     % tex_file_name_includable = [tex_name, '_', num2str(idx), '.tex'];
      fig = {'\begin{figure}[H]';                                            ... 
	         '\centering';                                                     ... 
	         ['\input{', tex_name, '_', num2str(idx), '.tex', '}'];            ... 
        	 ['\caption[',tex_name, '\_', num2str(idx), '.tex', ']'];          ... 
	         '{';                                                              ... 
		       '    \lipsum[1]';                                                 ... 
	         '}';                                                              ... 
           '\end{figure}';                                                   ... 
           ['\lipsum[2]' char(10)];                                          ... 
          };

      export = [export ; fig;];
    end

    export = [export ; '\end{document}'];

    path = [filesep,'tikz', filesep, tex_name, filesep, 'includable', filesep];    
    all_file_name = ['all_', tex_name, '_figures'];

    pathdel  = [fullfile(pwd, ['tikz', filesep, tex_name, filesep, 'includable', filesep])];
    delete_file_if_exists(pathdel, all_file_name, 'aux');
    delete_file_if_exists(pathdel, all_file_name, 'log');
    delete_file_if_exists(pathdel, all_file_name, 'synctex.gz');
    delete_file_if_exists(pathdel, all_file_name, 'tex');
    delete_file_if_exists(pathdel, all_file_name, 'pdf');

    disp(['saving all images in one texfile at: ', path, all_file_name, '.tex']);

    fileID = fopen(['.', path, all_file_name, '.tex'], 'w');
    fprintf(fileID, '%s\n', export{:});
    fclose(fileID);
end
